spring:
  datasource:
    url: jdbc:postgresql://ec2-3-234-204-26.compute-1.amazonaws.com/derhebtvinbc1i
    username: ucidxcwzxstlkk
    password: fbd876f18835eb295907ae54dba73cc0d1f0b41a95c6628dd22cdf16a7b09940

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  #extras
  main:
    lazy-initialization: false
  quartz:
    scheduler-name: Omar Enrique Rafael Toribio
  graphql:
    cors:
      allowed-headers: *
      allowed-methods: *
  mvc:
    formcontent:
      filter:
        enabled: true
  config:
    activate:
      on-cloud-platform: heroku


server:
  port: 3013

jwt:
  jwtCookieName: access_token
  jwtSecret: 7638792F423F4528482B4D6251655368566D597133743677397A24432646294A
  jwtExpirationMs: 86400000
